mkdir js es6js css images local less jade maps
mkdir bundle\css
mkdir bundle\js 
mkdir bundle\img
mkdir bundle\local


echo # Logs >>.gitignore
echo logs >>.gitignore
echo *.log >>.gitignore
echo npm-debug.log* >>.gitignore

echo # Runtime data >>.gitignore
echo pids >>.gitignore
echo *.pid >>.gitignore
echo *.seed >>.gitignore

echo # Directory for instrumented libs generated by echo jscoverage/JSCover >>.gitignore
echo lib-cov >>.gitignore

echo # Coverage directory used by tools like istanbul >>.gitignore
echo coverage >>.gitignore

echo # nyc test coverage >>.gitignore
echo .nyc_output >>.gitignore

echo # Grunt intermediate storage (http://gruntjs.com/creating-echo plugins#storing-task-files) >>.gitignore
echo .grunt >>.gitignore

echo # node-waf configuration >>.gitignore
echo .lock-wscript >>.gitignore

echo # Compiled binary addons (http://nodejs.org/api/addons.html) >>.gitignore
echo build/Release >>.gitignore

echo # Dependency directories >>.gitignore
echo node_modules >>.gitignore
echo jspm_packages >>.gitignore

echo # Optional npm cache directory >>.gitignore
echo .npm >>.gitignore

echo # Optional REPL history >>.gitignore
echo .node_repl_history >>.gitignore

echo # @hzp >>.gitignore
echo psd >>.gitignore
echo PSD >>.gitignore
echo local >>.gitignore
echo .DS_Store >>.gitignore
